name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
          cmake --build . --config Release

      - name: Pack
        if: startsWith(matrix.os,'ubuntu')
        run: |
          cd build
          cpack -G DEB -DCPACK_PACKAGE_NAME="foo"
