name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - name: ubuntu-latest
            os: ubuntu-latest
            cpack-executable: 'cpack'
            cpack-generator: DEB
          - name: macos-latest
            os: ubuntu-latest
            cpack-executable: 'cpack'
            cpack-generator: ZIP
          - name: windows-latest
            os: windows-latest
            cpack-executable: '%PROGRAMFILES%/CMake/bin/cpack.exe'
            cpack-generator: ZIP


    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
          cmake --build . --config Release
          ${{matrix.cpack-executable}} -G ${{matrix.cpack-generator}}
