name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      project-version: "0.1.1"
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCPACK_PACKAGE_CONTACT="evpobr" -DCPACK_DEBIAN_PACKAGE_SHLIBDEPS=ON
          cmake --build . --config Release

      - name: Pack
        if: startsWith(matrix.os,'ubuntu')
        run: |
          cd build
          cpack -G DEB

      - uses: actions/upload-artifact@v1
        if: startsWith(matrix.os,'ubuntu')
        with:
          name: foo-${{project-version}}-Linux.deb
          path: build/foo-${{project-version}}-Linux.deb
